spring.application.name=PlayControl
spring.datasource.username=postgres
spring.datasource.password=PlayControlAWSPass123
spring.datasource.url=jdbc:postgresql://playcontroldb.c54um4s2it53.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexión a PostgreSQL (crea antes la BD playcontroldb en pgAdmin)
# Hibernate: genera y actualiza las tablas automáticamente

spring.jpa.properties.hibernate.format_sql=true

# Ruta de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs